### ISSUE TITLE
Justinian I & Constantine I INFO MISSING

### ISSUE THREAD

**Issue by Narrosh** [robbyae/hagia-sophia-mosaic#1]
Despite not having a specialized art historian, I think some viewers could appreciate at least some historical contextual info beyond the "Lorem Ipsum" placeholder text.

**Comment by robbyae** [comment]
Hey Narrosh. Thanks for your feedback. Because I am an antisocial nerd with nothing better to do, I have resolved this issue. Hopefully you learn something cool.
